# action.yml
name: Build Meteor Mongo from SRC

on:
  push:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@2
      - name: Run builder
        run: ./run-builder.sh
