# action.yml
name: Build Meteor Mongo from SRC

on:
  push:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2.3.1
      - name: Install GCC 5
        run: sudo apt install gcc-5 g++-5 libstdc++-5-dev -y
      - name: Run builder
        run: ./run-builder.sh
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.tgz'
